name: Java CI with Maven

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Verify setting.xml
        run: |
          ls -al $GITHUB_WORKSPACE
          test -f $GITHUB_WORKSPACE/setting.xml && echo "setting.xml found"

      - name: Build and analyze with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=dheasrinoorseptianiz -Dsonar.projectKey=dheasrinoorseptianiz_MKEPL-Latihan

      - name: Publish to GitHub Packages Apache Maven
        if: github.event_name == 'release'
        run: mvn -B deploy -s $GITHUB_WORKSPACE/setting.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
